from __future__ import annotations
from typing import Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from src.runtime.core.executor import RuntimeExecutor

from src.runtime.core.scheduling_model import SchedulingDecision, SchedulingStatus
from src.runtime.execution.runtime_execution_identity import RuntimeExecutionIdentity
from src.runtime.execution.runtime_execution_result import RuntimeExecutionResult


class RuntimeExecutionCoordinator:
    """
    The canonical Runtime authority for execution handoff coordination.
    
    Responsibilities:
    - Coordinate an accepted SchedulingDecision into RuntimeExecutor.
    - Preserve RuntimeExecutionIdentity exactly.
    - Preserve RuntimeExecutionResult exactly.
    - Prevent execution of non-READY scheduling decisions.
    
    Must NEVER:
    - Execute workloads or invoke providers (Executor does this).
    - Manage state transitions.
    - Mutate sessions.
    - Translate or catch exceptions for re-classification.
    - Inspect or modify failure outcomes.
    """
    
    def __init__(self, executor: RuntimeExecutor) -> None:
        self._executor = executor

    def coordinate(
        self,
        scheduling_decision: SchedulingDecision,
        identity: RuntimeExecutionIdentity,
    ) -> Optional[RuntimeExecutionResult]:
        """
        Evaluate the scheduling decision and orchestrate the execution handoff.
        
        Returns None if the decision is not READY (e.g. REJECTED, QUEUED, BLOCKED, DEFERRED), representing no execution.
        Returns the exact RuntimeExecutionResult generated by the RuntimeExecutor otherwise.
        """
        if scheduling_decision.status != SchedulingStatus.READY:
            return None
            
        return self._executor.execute(
            scheduling_decision=scheduling_decision,
            identity=identity
        )
