"""add_jobs_table

Revision ID: b8cfb9b9225b
Revises: 9f476b0eafb1
Create Date: 2026-08-11 01:45:43.377003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8cfb9b9225b'
down_revision: Union[str, Sequence[str], None] = '9f476b0eafb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'ACCEPTED', 'QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('previous_status', sa.Enum('REQUESTED', 'ACCEPTED', 'QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status_updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_requested', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcripts',
    sa.Column('video_asset_id', sa.String(), nullable=False),
    sa.Column('full_text', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_asset_id'], ['video_assets.id'], ),
    sa.PrimaryKeyConstraint('video_asset_id')
    )
    op.create_table('video_knowledge_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('video_asset_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('knowledge_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['video_asset_id'], ['video_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_knowledge_snapshots_video_asset_id'), 'video_knowledge_snapshots', ['video_asset_id'], unique=False)
    op.create_table('transcript_segments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('video_asset_id', sa.String(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('speaker', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['video_asset_id'], ['transcripts.video_asset_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_segments_video_asset_id'), 'transcript_segments', ['video_asset_id'], unique=False)
    op.create_table('transcript_words',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('segment_id', sa.String(), nullable=False),
    sa.Column('word_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('speaker', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['transcript_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcript_words')
    op.drop_index(op.f('ix_transcript_segments_video_asset_id'), table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_index(op.f('ix_video_knowledge_snapshots_video_asset_id'), table_name='video_knowledge_snapshots')
    op.drop_table('video_knowledge_snapshots')
    op.drop_table('transcripts')
    op.drop_table('jobs')
    # ### end Alembic commands ###
