from typing import Protocol, List
import uuid
from .entities import (
    WordLevelTimestamp, SpeakerSegment, EnergySegment, SilenceSegment,
    SceneBoundary, FaceBoundingBox, EmotionSegment, GestureEvent,
    ObjectDetection, OCREvent, TopicSegment, TimelineContext, ClipSegment,
    Project, VideoAsset
)

# --- PHASE 1 & 2: AUDIO MODALITIES ---
class IAudioAnalyzer(Protocol):
    """Handles Transcription, Diarization, Energy, and Silence detection"""
    def transcribe(self, audio_path: str) -> List[WordLevelTimestamp]: ...
    def detect_speakers(self, audio_path: str) -> List[SpeakerSegment]: ...
    def measure_energy(self, audio_path: str) -> List[EnergySegment]: ...
    def detect_silence(self, audio_path: str) -> List[SilenceSegment]: ...

# --- PHASE 3: VISUAL MODALITIES ---
class IVisionAnalyzer(Protocol):
    """Handles Scenes, Faces, Emotions, Gestures, Objects, and OCR"""
    def detect_scenes(self, video_path: str) -> List[SceneBoundary]: ...
    def detect_faces(self, video_path: str, fps: int = 1) -> List[FaceBoundingBox]: ...
    def detect_emotions(self, video_path: str, fps: int = 1) -> List[EmotionSegment]: ...
    def detect_gestures(self, video_path: str, fps: int = 1) -> List[GestureEvent]: ...
    def detect_objects(self, video_path: str, fps: int = 1) -> List[ObjectDetection]: ...
    def read_text_ocr(self, video_path: str, fps: int = 1) -> List[OCREvent]: ...

# --- PHASE 4 & 5: SEMANTIC & REASONING (LLM) ---
class ILLMReasoningEngine(Protocol):
    """Uses the central TimelineContext to perform heavy semantic reasoning"""
    def detect_topics(self, text_transcript: str) -> List[TopicSegment]: ...
    def generate_clips(self, context: TimelineContext) -> List[ClipSegment]: ...
    def rank_clips(self, clips: List[ClipSegment], context: TimelineContext) -> List[ClipSegment]: ...

# --- INFRASTRUCTURE PORTS ---
class IVideoProcessor(Protocol):
    def extract_audio(self, video_path: str, output_path: str) -> None: ...
    def extract_frames(self, video_path: str, output_dir: str, fps: int = 1) -> None: ...
    def render_clip(self, clip: ClipSegment, output_path: str) -> None: ...
    def get_video_metadata(self, video_path: str) -> dict: ...

class IProjectRepository(Protocol):
    def save_project(self, project: Project) -> None: ...
    def get_project(self, project_id: uuid.UUID) -> Project: ...
    def save_clips(self, clips: List[ClipSegment]) -> None: ...
    def get_clips_for_video(self, video_asset_id: uuid.UUID) -> List[ClipSegment]: ...

class IVideoRepository(Protocol):
    async def save_video(self, video: VideoAsset) -> None: ...
    async def get_video(self, video_id: uuid.UUID) -> VideoAsset: ...
    async def delete_video(self, video_id: uuid.UUID) -> None: ...
    async def get_videos_for_project(self, project_id: uuid.UUID) -> List[VideoAsset]: ...

class ITimelineContextRepository(Protocol):
    def save_context(self, context: TimelineContext) -> None: ...
    def get_context(self, video_asset_id: uuid.UUID) -> TimelineContext: ...

# --- CAMPAIGN INTELLIGENCE PORTS ---
from .campaign_entities import Campaign, CampaignRules, CampaignSummary, WorthItScore

class ICampaignParser(Protocol):
    """Parses raw input (URL, PDF, Text) into raw string text"""
    async def parse(self, source: str, content_type: str) -> str: ...

class ICampaignIntelligence(Protocol):
    """Uses LLM to extract structured campaign rules and summaries from raw text"""
    async def extract_rules(self, text: str) -> CampaignRules: ...
    async def generate_summary(self, text: str) -> CampaignSummary: ...
    async def calculate_worth_it_score(self, text: str, rules: CampaignRules) -> WorthItScore: ...

class ICampaignRepository(Protocol):
    """Persistence for Campaigns"""
    async def save_campaign(self, campaign: Campaign) -> None: ...
    async def get_campaign(self, campaign_id: uuid.UUID) -> Campaign: ...
    async def get_all_campaigns(self, limit: int = 50, skip: int = 0) -> List[Campaign]: ...

