from typing import Protocol, List, Sequence
import uuid
from src.domain.render_plan import RenderPlan
from src.domain.models.render_result import RenderResult
from src.domain.campaign_entities import (
    Campaign, CampaignRules, CampaignSummary, WorthItScore, CampaignImportHistory,
    CampaignExecutionPlan, CampaignClipStrategy, CampaignPromptTemplate, CampaignSuitabilityAssessment,
    PlanningPipelineResult
)
from src.domain.entities import (
    WordLevelTimestamp, SpeakerSegment, EnergySegment, SilenceSegment,
    SceneBoundary, FaceBoundingBox, EmotionSegment, GestureEvent,
    ObjectDetection, OCREvent, TopicSegment, TimelineContext, ClipSegment,
    Project, VideoAsset
)
from src.domain.job import Job

# --- PHASE 1 & 2: AUDIO MODALITIES ---
class IAudioAnalyzer(Protocol):
    """Handles Transcription, Diarization, Energy, and Silence detection"""
    def transcribe(self, audio_path: str) -> List[WordLevelTimestamp]: ...
    def detect_speakers(self, audio_path: str) -> List[SpeakerSegment]: ...
    def measure_energy(self, audio_path: str) -> List[EnergySegment]: ...
    def detect_silence(self, audio_path: str) -> List[SilenceSegment]: ...

# --- PHASE 3: VISUAL MODALITIES ---
class IVisionAnalyzer(Protocol):
    """Handles Scenes, Faces, Emotions, Gestures, Objects, and OCR"""
    def detect_scenes(self, video_path: str) -> List[SceneBoundary]: ...
    def detect_faces(self, video_path: str, fps: int = 1) -> List[FaceBoundingBox]: ...
    def detect_emotions(self, video_path: str, fps: int = 1) -> List[EmotionSegment]: ...
    def detect_gestures(self, video_path: str, fps: int = 1) -> List[GestureEvent]: ...
    def detect_objects(self, video_path: str, fps: int = 1) -> List[ObjectDetection]: ...
    def read_text_ocr(self, video_path: str, fps: int = 1) -> List[OCREvent]: ...

# --- PHASE 4 & 5: SEMANTIC & REASONING (LLM) ---
class ILLMReasoningEngine(Protocol):
    """Uses the central TimelineContext to perform heavy semantic reasoning"""
    def detect_topics(self, text_transcript: str) -> List[TopicSegment]: ...
    def generate_clips(self, context: TimelineContext) -> List[ClipSegment]: ...
    def rank_clips(self, clips: List[ClipSegment], context: TimelineContext) -> List[ClipSegment]: ...

class IRenderBackend(Protocol):
    """
    Rendering backend abstraction.
    It owns exactly one responsibility: Execute a RenderPlan.
    """
    def execute(self, plan: RenderPlan) -> RenderResult: ...

class IVideoProcessor(Protocol):
    def extract_audio(self, video_path: str, output_path: str) -> None: ...
    def extract_frames(self, video_path: str, output_dir: str, fps: int = 1) -> None: ...
    def render_clip(self, clip: ClipSegment, output_path: str) -> None: ...
    def get_video_metadata(self, video_path: str) -> dict: ...

class IProjectRepository(Protocol):
    async def create(self, project: Project) -> Project: ...
    async def get_by_id(self, project_id: str) -> Project | None: ...
    async def get_by_name(self, name: str) -> Project | None: ...
    async def get_all(self, skip: int = 0, limit: int = 50) -> Sequence[Project]: ...
    async def delete(self, project: Project) -> None: ...
    async def count(self) -> int: ...
    
    async def save_project(self, project: Project) -> None: ...
    async def get_project(self, project_id: uuid.UUID) -> Project: ...
    async def save_clips(self, clips: List[ClipSegment]) -> None: ...
    async def get_clips_for_video(self, video_asset_id: uuid.UUID) -> List[ClipSegment]: ...

class IUploadFile(Protocol):
    """Protocol for injected file streams in services."""
    @property
    def filename(self) -> str | None: ...
    @property
    def content_type(self) -> str | None: ...
    async def read(self, size: int) -> bytes: ...

class IVideoRepository(Protocol):
    async def save_video(self, video: VideoAsset) -> None: ...
    async def get_video(self, video_id: uuid.UUID) -> VideoAsset: ...
    async def delete_video(self, video_id: uuid.UUID) -> None: ...
    async def get_videos_for_project(self, project_id: uuid.UUID) -> List[VideoAsset]: ...

class ITimelineContextRepository(Protocol):
    async def save_context(self, context: TimelineContext) -> None: ...
    async def get_context(self, video_asset_id: uuid.UUID) -> TimelineContext: ...

class ICampaignNormalizationService(Protocol):
    """Normalizes raw campaign text before intelligence extraction"""
    def normalize(self, raw_text: str) -> str: ...

class ICampaignParser(Protocol):
    """Parses raw input (URL, PDF, Text) into raw string text"""
    async def parse(self, source: str, content_type: str) -> str: ...

class ICampaignIntelligence(Protocol):
    """Uses LLM to extract structured campaign rules and summaries from raw text"""
    async def extract_rules(self, text: str) -> CampaignRules: ...
    async def generate_summary(self, text: str) -> CampaignSummary: ...
    async def calculate_worth_it_score(self, text: str, rules: CampaignRules) -> WorthItScore: ...
    
    async def generate_execution_plan(self, campaign: Campaign) -> CampaignExecutionPlan: ...
    async def generate_clip_strategy(self, campaign: Campaign, plan: CampaignExecutionPlan) -> CampaignClipStrategy: ...
    async def generate_prompt_template(self, campaign: Campaign, plan: CampaignExecutionPlan, strategy: CampaignClipStrategy) -> CampaignPromptTemplate: ...
    async def assess_suitability(self, campaign: Campaign) -> CampaignSuitabilityAssessment: ...

class ICampaignRepository(Protocol):
    """Persistence for Campaigns"""
    async def save_campaign(self, campaign: Campaign) -> None: ...
    async def get_campaign(self, campaign_id: uuid.UUID) -> Campaign: ...
    async def get_all_campaigns(self, limit: int = 50, skip: int = 0) -> List[Campaign]: ...
    async def find_potential_duplicates(self, campaign_url: str, title: str, brand: str) -> List[Campaign]: ...
    async def save_import_history(self, history: CampaignImportHistory) -> None: ...
    async def get_import_history(self, limit: int = 50, skip: int = 0) -> List[CampaignImportHistory]: ...
    
    async def save_planning_result(self, result: PlanningPipelineResult) -> None: ...
    async def get_planning_result(self, campaign_id: uuid.UUID) -> PlanningPipelineResult: ...
    async def get_planning_history(self, campaign_id: uuid.UUID) -> List[PlanningPipelineResult]: ...
    async def delete_planning_result(self, campaign_id: uuid.UUID) -> None: ...

class IJobRepository(Protocol):
    """Persistence for Workflow Jobs"""
    async def save(self, job: Job) -> None: ...
    async def get(self, job_id: uuid.UUID) -> Job | None: ...

class IWorkflowDispatcher(Protocol):
    """
    Technology-agnostic dispatcher for asynchronous workflows.
    Should orchestrate execution by invoking domain transition methods (e.g. queue, start, complete, fail).
    """
    async def dispatch(self, job: Job, task_callable, *args, **kwargs) -> None: ...
