from dataclasses import dataclass, field
from typing import Tuple

from src.reasoning.execution.models import ExecutionInput


@dataclass(frozen=True)
class DraftSegment:
    """
    Represents a candidate segment in a draft execution plan.
    Does not contain UUIDs generated by the planner, external state,
    or rendering operations. It is deterministic and immutable.
    """
    start_time: float
    end_time: float
    purpose: str
    tags: Tuple[str, ...]
    reasoning: str


@dataclass(frozen=True)
class ExecutionPlanDraft:
    """
    Represents the deterministic output of the Execution Planner.
    Preserves traceability to the ExecutionInput without constructing
    an ExecutionPlan. Exists to maintain clear ownership boundaries.
    """
    execution_input: ExecutionInput
    segments: Tuple[DraftSegment, ...]
